# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update plots

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate plots
      run: |
        python mittelmann_plots.py update
    - uses: EndBug/add-and-commit@v4
      with:
        add: 'docs'
        # The name of the user that will be displayed as the author of the commit
        author_name: Matthias Miltenberger
        # The email of the user that will be displayed as the author of the commit
        author_email: matthias.miltenberger@gmail.com
        # The message for the commit
        message: 'Update plots'

      env:
        # This is necessary in order to push a commit to the repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
